#!/usr/bin/env bash
# Displays "Best School" a using while loop.

# Initialize count
count=0

# Using a while loop to display "Best School" 10 times
while [ $count -lt 10 ]
do
      echo "Best School"
      # Increment count
      (( count++ ))
done
